couchbase/couchbase-lite-C

README.md

* c sample was using cpp method `_fl` of fleece or i was not able to run with it. 
* `FLSlot` used instead of directly setting `FLMutableDict_SetString`.

fix: c sample using cpp methods

---

src/CBLLog.cc

Fix build error

---

bindings/python/BuildPyCBL.py

Introduce optional --python_includedir argument to BuildPyCBL.py,
so that the target's headers (e.g. from an SDK) can be supplied instead
of using python headers from the build system itself.
It is always a good idea to use the right set of headers, but python
headers do a sanity check that fails the build if the target is 32-bit
but headers come from a 64-bit build system:
#error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."

BuildPyCBL.py: support cross-compile for python bindings

---

bindings/nim/README.md
bindings/nim/src/CouchbaseLite/database.nim
bindings/nim/src/CouchbaseLite/document.nim
bindings/nim/src/CouchbaseLite/errors.nim
bindings/nim/src/CouchbaseLite/fleece.nim
bindings/nim/src/CouchbaseLite/listener.nim
bindings/nim/src/CouchbaseLite/private/cbl.nim
bindings/nim/src/CouchbaseLite/private/fl.nim
bindings/nim/src/CouchbaseLite/query.nim
bindings/nim/src/CouchbaseLite/replicator.nim
bindings/nim/tests/test2Database.nim

This fixes various style issues in the Nim bindings, mostly by passing it through nimpretty, but also some manual tweaks. It is based on the betternim branch and so includes those commits as well.

Fix various style issues in the Nim bindings

---

bindings/python/CouchbaseLite/common.py

* fix sliceRestulToBytes param ref
* fix FLSlice ref

Minor fixes to common.py

---

bindings/python/CouchbaseLite/Collections.py

Fix MutableArray delitem

---

include/cbl++/Replicator.hh

Add method for authentification using the session ID and the cookie name.

Add session based authentification

---

include/cbl++/Database.hh
include/cbl/CBLDatabase.h
src/CBLDatabase.cc
src/exports/CBL.def
src/exports/CBL.exp
src/exports/generated/CBL.exp
test/BlobTest_Cpp.cc
test/DatabaseTest.cc

* Added CBLDatabase_PerformMaintenance() function
* Marked CBLDatabase_Compact() as deprecated.
* Added performMaintenance() to c++ API as well.

CBL-1589: Add CBLDatabase_PerformMaintenance()

---

.github/workflows/build.yml
.github/workflows/xcodebuild.yml
include/cbl++/Database.hh
test/CBLTest.cc

Config file adapted from LiteCore's

Adding Github CI

---

include/cbl++/Database.hh
include/cbl++/Query.hh
include/cbl/CBLQuery.h
src/CBLDatabase_CAPI.cc
src/CBLDatabase_Internal.hh
src/CBLQuery_CAPI.cc
src/exports/CBL_Exports.txt
src/exports/generated/CBL.def
src/exports/generated/CBL.exp
src/exports/generated/CBL.gnu
src/exports/generated/CBL_EE.def
src/exports/generated/CBL_EE.exp
src/exports/generated/CBL_EE.gnu
test/DatabaseTest.cc
test/QueryTest.cc

* Changed CBLQuery_New to CBLDatabase_CreateQuery()
* Changed CBLValueIndex to CBLValueIndexConfiguration
* Changed CBLFullTextIndex to CBLFullTextIndexConfiguration
* ~~Renamed kCBLN1QLLanguage to kCBLStringLanguage as N1QL term should not be used in the API.~~
* Updated Lite-Core and fixed build issue in creating index code.
* Fixed race condition in Query Listener Test.

Revise the Query API to be more inline with the other platforms

---

src/CBLDatabase+Apple.mm

* Used URLForDirectory with create enabled instead of NSSearchPathForDirectoriesInDomains per code review’s suggestion.
* Added a proper assertion to check the path instead of letting it crash as it cannot create std::string from null value.

Use URLForDirectory with create enabled instead of NSSearchPathForDirectoriesInDomains

---

CMakeLists.txt
scripts/coverage.sh

Added scripts/coverage.sh and update cmake for generating code coverage.

Add script for generating code coverage

---

test/QueryTest.cc

Add more query tests

---

include/cbl/CBLDatabase.h
test/DatabaseTest.cc

* Added Optimize and FullOptimize Maintenance Mode
* Added sanity tests for both modes.

Add Optimize and FullOptimize Maintenance Mode

---

test/QueryTest.cc

* Updated LiteCore
* Fixed N1QL without FROM in QueryTest

Update LiteCore and Fix N1QL without FROM in QueryTest

---

src/CBLDocument_CAPI.cc
src/CBLDocument_Internal.hh
src/CBLPrivate.h
src/ConflictResolver.cc
src/ConflictResolver.hh
src/exports/CBL_Exports.txt
src/exports/generated/CBL.def
src/exports/generated/CBL.exp
src/exports/generated/CBL.gnu
src/exports/generated/CBL_EE.def
src/exports/generated/CBL_EE.exp
src/exports/generated/CBL_EE.gnu
test/ReplicatorEETest.cc

* Fixed default conflict resolution logic for replictor.
* Added private API to get generation of the document.
* Added tests.

CBL-2144 : Fix default conflict resolution

---

include/cbl++/Replicator.hh
include/cbl/CBLReplicator.h
src/CBLReplicatorConfig.hh
src/CBLReplicator_CAPI.cc
test/ReplicatorTest.cc
test/ReplicatorTest.hh

* Change CBLEndpoint_CreateWithURL API to be able to return an error when the URL is invalid.
* Validate the specified URL and its scheme and return an error if the validation fails.

CBL-2179 : Change CBLEndpoint_CreateWithURL to return error

---

include/cbl++/Base.hh
include/cbl++/Database.hh
include/cbl++/Document.hh
include/cbl/CBLBase.h
include/cbl/CBLLog.h
src/CBLBlob_Internal.hh
src/CBLLog.cc
test/CBLTest.cc
test/DatabaseTest.cc
test/DatabaseTest_Cpp.cc
test/LogTest.cc
test/QueryTest.cc
test/ReplicatorTest.cc

Fixed enum values that are not prefixed with k including CBLLogLevel, CBLErrorDomain, CBLErrorCode, and CBLNetworkErrorCode.

Fixed enum values that are not prefixed with k

---

include/cbl/CBLBlob.h
src/CBLBlob_Internal.hh
src/CBLDatabase.cc
src/CBLDatabase_CAPI.cc
src/CBLDatabase_Internal.hh
src/exports/CBL_Exports.txt
src/exports/generated/CBL.def
src/exports/generated/CBL.exp
src/exports/generated/CBL.gnu
src/exports/generated/CBL_EE.def
src/exports/generated/CBL_EE.exp
src/exports/generated/CBL_EE.gnu
test/DatabaseTest.cc

Implemented Database_GetBlob() and Database_SaveBlob() and added tests.

CBL-2190 : Implement Database_GetBlob and SaveBlob

---

include/cbl/CBLReplicator.h
src/CBLBlob_CAPI.cc
src/ConflictResolver.cc
test/ReplicatorEETest.cc

Fix logic in CBLDefaultConflictResolver

---

include/cbl/CBLDocument.h
test/DatabaseTest.cc

* Add small notes about what to use for getting nested collections as mutable collections.
* Add tests for confirming the behavior.

Add note about getting nested collections as mutable

---

CBL_C.xcodeproj/xcshareddata/xcschemes/Doxygen.xcscheme
Doxyfile

Doxygen warned that the config file was out of date, so I allowed it to update
the file. Looks like this bumped the version number at the top, updated a bunch
of comments, added new configs with default values, etc.
I did not make manual changes to the file.
I also added an Xcode scheme to run the "Doxygen" target, which builds the docs.

Updated Doxyfile for newer Doxygen, added Xcode scheme

---

src/exports/CBL_Exports.txt
src/exports/generated/CBL.def
src/exports/generated/CBL.exp
src/exports/generated/CBL.gnu
src/exports/generated/CBL_Android.gnu
src/exports/generated/CBL_EE.def
src/exports/generated/CBL_EE.exp
src/exports/generated/CBL_EE.gnu
src/exports/generated/CBL_EE_Android.gnu

Fix missing CBLBlob_CreateJSON exported symbol

---

src/CBLDatabase+Apple.mm

The default database parent directory (in the default configuration) is not
created automatically. This makes creating a database fail until you create the
directory yourself, which is very unintuitive. Fixed.
CBL-2389

CBLDatabase+Apple.mm: Create config dir if it doesn't exist (CBL-2389)

---

include/cbl/CBLEncryptable.h
test/ReplicatorPropEncTest.cc

Add FLMutableDict_SetEncryptableValue

---

src/CBLDocument.cc

Minor cleanup saveBlobsAndCheckEncryptables

---

CMakeLists.txt

Updated LiteCore and Linked with the new object bundles.

Update LiteCore and use the new object bundles

---

src/CBLCollection_CAPI.cc
test/CollectionTest.cc

* Added more collection tests
* Removed upgrade tests as those are normally done by functional tests.
* Fixed missing try/catch in CBLDatabase_DefaultCollection.

CBL-3185 : Add more collection tests

---

src/CBLCollection_CAPI.cc
src/CBLDatabase.cc
src/CBLDatabase_Internal.hh

* Updated LiteCore to get c4db’s hasScope() and updated the code to use it.
* Corrected const declartion on some of the functions which are not const internally.

Update to use hasScope and fix const declaration

---

CBL_C.xcodeproj/project.pbxproj
src/CBLBase_CAPI.cc
src/CBLCollection_CAPI.cc
src/CBLDatabase_CAPI.cc
src/CBLDocument_CAPI.cc
src/CBLLog.cc
src/CBLPrivate.h
src/exports/CBL_Exports.txt
src/exports/generated/CBL.def
src/exports/generated/CBL.exp
src/exports/generated/CBL.gnu
src/exports/generated/CBL_Android.gnu
src/exports/generated/CBL_EE.def
src/exports/generated/CBL_EE.exp
src/exports/generated/CBL_EE.gnu
src/exports/generated/CBL_EE_Android.gnu
test/CBLTest.cc
test/CBLTest.hh
test/CMakeLists.txt
test/CollectionTest.cc
test/DatabaseTest.cc
test/ReplicatorCollectionTest.cc
test/ReplicatorPropEncTest.cc
test/ReplicatorTest.cc
test/ReplicatorTest.hh

* Added Replicator Collection Tests
* Added CBLCollection_Database to private API used in tests.
* Moved some test utility functions to CBLTest so that they can be shared.

CBL-3513 : Add Replicator Collection Tests

---

test/QueryTest.cc
test/ReplicatorCollectionTest.cc
test/ReplicatorTest.hh

Added query tests with collections.

CBL-3566 - Add query tests with collections

---

CBL_C.xcodeproj/project.pbxproj
include/cbl++/Collection.hh
include/cbl++/CouchbaseLite.hh
include/cbl++/Database.hh
include/cbl++/Document.hh
test/CBLTest.cc
test/CBLTest_Cpp.hh
test/CMakeLists.txt
test/CollectionTest_Cpp.cc
test/DatabaseTest_Cpp.cc
test/DocumentTest_Cpp.cc

* Implemented C++ Collection API. For simplicity omitting Scope class for now. Scope class could come later when there is a scope feature such as change listener and query with scope context.
* Added CollectionTest_Cpp and DocumentTest_Cpp.
* API Docs will come later together with the other parts of the API.

CBL-3255 : Implement C++ Collection API

---

scripts/coverage_cpp_macos.sh
test/DatabaseTest_Cpp.cc

* Added a script for generating code coverage for CPP API (Note: This report is not push to the PR yet. I will work on his separately).
* Added more tests for Database.hh.

CBL-2783 : Add more C++ Database tests

---

src/CBLCollection_Internal.hh
src/CBLDatabase_Internal.hh
src/ConflictResolver.cc
src/ConflictResolver.hh

Removed unused AllConflictsResolver found while reviewing the code coverage.

Remove unused AllConflictsResolver

---

test/BlobTest.cc
test/DatabaseTest.cc
test/DocumentTest.cc
test/QueryTest.cc

* Added a test for FLValue_IsBlob.
* Added a test for FLMutableArray_AppendBlob and FLMutableArray_SetBlob.
* Added a test for CBLEncryptionKey_FromPasswordOld.
* Updated a test for testing creating a query with JSON.

Add some more tests

---

include/cbl++/Base.hh
test/DatabaseTest_Cpp.cc

* The issue was reported from the forum that the Query’s ListenerToken (Query::ChangeListener) is not moveable due to the _callback member, which is an unmovable unique_ptr.
* In ListenerToken class, changed _callback from unique_ptr to shared_ptr which allows to move.
* In ListenerToken class, explicitly called to move other’s _callback in move assignment operator.
* Added the missing nullable return type tag to the ListenerToken.token() function.
* Added ListenerToken Tests.

CBL-2815 : Fix C++ ListenerToken move ctor and assignment

---

Xcode/CouchbaseLite.modulemap

Added missing header files in framework modulemap file.

Fix framework modulemap file

---

test/CBLTest.cc
test/CollectionTest.cc

Fixed XCode warning on using sprintf.

Use snprintf instead of sprintf

---

jenkins/ci_cross_build.py

Refactor of https://github.com/couchbase/couchbase-lite-C/pull/391

CVE-2007-4559 Patch refactor

---

jenkins/ci_build_win_desktop.ps1

* Added the Architecture argument (default x64 or ARM64) for selecting the architecture.
* Tested on a Windows laptop.

CBL-3864 : Update windows build script to support ARM64 build

---

test/CBLTest.cc
test/CBLTest_Cpp.hh
test/ReplicatorCollectionTest.cc
test/ReplicatorCollectionTest_Cpp.cc
test/ReplicatorEETest.cc
test/ReplicatorPropEncTest.cc

- collated the **two** into CBLTest_Cpp::openDatabaseNamed(name, empty = true)
- updated callbacks

CBL-3931: Combine two openDatabaseNamed in C++ test

---

CBL_C.xcodeproj/project.pbxproj
src/CBLPrivate.h
src/CBLReplicatorConfig.hh
src/CBLReplicator_CAPI.cc
src/CBLReplicator_Internal.hh
src/CBLUserAgent.hh
src/exports/CBL_Exports.txt
src/exports/generated/CBL.def
src/exports/generated/CBL.exp
src/exports/generated/CBL.gnu
src/exports/generated/CBL_Android.gnu
src/exports/generated/CBL_EE.def
src/exports/generated/CBL_EE.exp
src/exports/generated/CBL_EE.gnu
src/exports/generated/CBL_EE_Android.gnu
test/ReplicatorTest.cc

- simple default template and test
- enhancing to follow as separate tickets for `git commit`, `Linux OS` and `Windows OS` related information.

CBL-3914: Add user-agent header to the replicator

---

src/CBLLog.cc

Write to android’s logcat for android’s console logging.

CBL-3914 : Use logcat for android console logging

---

test/platforms/Android/README.md

* Fixed libcbilte typo
* Fixed wrong running test command
* Removed $ on every sample command

Fix Android Test README

---

test/PerfTest.cc
test/platforms/Android/app/libs/build.sh

* Changed log tag to "CBLTests”.
* Added a convenient script for building libcblite for android tests.

Small update to android tests

---

src/CBLUserAgent.hh

Also cleaned up formatting a bit, and removed 32-bit Windows section since it is not supported.

CBL-3998: Include Windows version info in user agent

---

CBL_C.xcodeproj/project.pbxproj
cmake/platform_apple.cmake
src/CBLUserAgent.hh
src/CBLUserAgent.mm

If on an iOS device, this will print the device type (e.g. iPhone8,2) as well as the OS version

Add Apple version information to user agent

---

.github/workflows/xcodebuild.yml
CBL_C.xcodeproj/project.pbxproj
Xcode/xcconfigs/CBL_Dylib_Release.xcconfig
Xcode/xcconfigs/CBL_Framework.xcconfig
Xcode/xcconfigs/CBL_dylib.xcconfig
Xcode/xcconfigs/Tests.xcconfig
test/BlobTest_Cpp.cc
test/CBLTest.cc
test/QueryTest.cc

* Fixed empty identity is not valid error with XCode 14
* Used snprintf instead of sprintf
* Updated LiteCore to the latest lithium to fix build failure in Ubuntu 22

Fix build and test failures - lithium

---

CBL_C.xcodeproj/project.pbxproj
cmake/generate_edition.cmake
cmake/platform_apple.cmake
include/cbl/CBL_Edition.h.in
src/CBLPrivate.h
src/CBLReplicatorConfig.hh
src/CBLReplicator_CAPI.cc
src/CBLReplicator_Internal.hh
src/CBLUserAgent.hh
src/CBLUserAgent.mm
src/exports/CBL_Exports.txt
src/exports/generated/CBL.def
src/exports/generated/CBL.exp
src/exports/generated/CBL.gnu
src/exports/generated/CBL_Android.gnu
src/exports/generated/CBL_EE.def
src/exports/generated/CBL_EE.exp
src/exports/generated/CBL_EE.gnu
src/exports/generated/CBL_EE_Android.gnu
test/ReplicatorTest.cc

Back Ported from Master Branch:
* 3a32adb5c5c606b9c7531c4939c06814bc6ea0e4
* a8bbe081025d65c88afc8cbd739fbe83fad9cdef
* c55d30df97bb4aea3b5b8edd603236ae7fda7a60
* 1084bf9dec720bd73bcf6ab5d090f98b7e69ff23
* 1f25fa54adead109fa3e0db43cc876a956c1c70b
* e09f1393b6ab3f979a089e0636e30f02a93006a4
* 38c04fc21f89feff39f42a51f4e172fb72b387a9

CBL-3923 : Add User-Agent to Replicator Header

---

test/QueryTest.cc

Added Select All Result Key Test according to section 8.11.10 in Scope and Collection API spec.

CBL-4165 : Add Select All Result Key Test

---

test/CBLTest.cc
test/CBLTest.hh
test/CBLTest_Cpp.hh
test/CollectionTest.cc
test/CollectionTest_Cpp.cc
test/DatabaseTest.cc
test/DatabaseTest_Cpp.cc
test/QueryTest.cc
test/ReplicatorCollectionTest.cc
test/ReplicatorCollectionTest_Cpp.cc

Separated the new tests (ticket scope) from the extra refactoring into two commits.

CBL-4195: Add tests for collection listeners

---

test/QueryTest.cc

- fts with index on default and named collection using match and rank
- fts using join

CBL-4251: Add Test Query Tests from section 8.11.6 - 8.11.9

---

include/cbl/CBLReplicator.h

Added missing nullable propertyEncryptor and propertyDecryptor.

CBL-4349 : Add missing nullable propertyEncryptor/Decryptor

---

jenkins/ci_cross_build.py

* Ported the fix from the helium (820876ebd3e8d2f8b8ef8852b7a4fe25228c4e1a)
* See info / fix about CVE from the original PR : https://github.com/couchbase/couchbase-lite-C/pull/391

CBL-3876 : CVE-2007-4559 Patch

---

jenkins/ci_cross_build.py

To avoid a race between two jobs extracting to the same directory at the same time

CBL-4653: Download toolchain / sysroot to tmpdir and move

---

include/cbl++/Collection.hh
include/cbl/CBLCollection.h
src/CBLCollection_CAPI.cc
src/CBLCollection_Internal.hh
src/exports/CBL_Exports.txt
src/exports/generated/CBL.def
src/exports/generated/CBL.exp
src/exports/generated/CBL.gnu
src/exports/generated/CBL_Android.gnu
src/exports/generated/CBL_EE.def
src/exports/generated/CBL_EE.exp
src/exports/generated/CBL_EE.gnu
src/exports/generated/CBL_EE_Android.gnu
test/CollectionTest.cc
test/CollectionTest_Cpp.cc

Implemented collection’s fullName which is in "< scope-name >.< collection-name >" format.

CBL-5202 : Implement collection’s full name accessor

---

include/cbl++/Collection.hh
include/cbl++/Database.hh
include/cbl/CBLCollection.h
include/cbl/CBLScope.h
src/CBLCollection_CAPI.cc
src/CBLScope_CAPI.cc
src/CBLScope_Internal.hh
src/exports/CBL_Exports.txt
src/exports/generated/CBL.def
src/exports/generated/CBL.exp
src/exports/generated/CBL.gnu
src/exports/generated/CBL_Android.gnu
src/exports/generated/CBL_EE.def
src/exports/generated/CBL_EE.exp
src/exports/generated/CBL_EE.gnu
src/exports/generated/CBL_EE_Android.gnu
test/CollectionTest.cc
test/CollectionTest_Cpp.cc

* Implemented collection and scope database accessor.
* Note: No Scope object in C++ API (May add the Scope class if needed).

CBL-5208 : Implement collection and scope database accessor

---

CBL_C.xcodeproj/project.pbxproj
Xcode/PrivacyInfo.xcprivacy

Added Privacy Manifest File and bundled it into the Apple framework.

CBL-5389 : Add Apple Privacy Manifest File

---

src/CBLReplicator_Internal.hh

* Updated LiteCore to 3.2.0-148
* Generated replicator id as `CBL@< pointer address >`. May think about how to shortern this such as using a running number instead of using pointer address.

Update LiteCore to 3.2.0-148

---

CBL_C.xcodeproj/project.pbxproj
Xcode/PrivacyInfo.xcprivacy

Included PrivacyInfo.xcprivacy in iOS Framework as required by Apple.

CBL-5265 : Include PrivacyInfo.xcprivacy in iOS Framework

---

include/cbl/CBLPrediction.h

Add API doc for CBL_RegisterPredictiveModel and CBL_UnregisterPredictiveModel.

Add API doc for register/unregister predictive model function

---

jenkins/ci_build_unix.sh
jenkins/ci_build_win_desktop.ps1
test/VectorSearchTest.cc

* Downloaded VS Search in CI Build for testing.
* Disabled VS Search on Windows ARM64 for now as we don’t release it in 3.2.0 beta-3.

CBL-5786 : Download VS Search in CI Build for testing

---

src/CBLDatabase_Internal.hh
src/CBLReplicatorConfig.hh
src/CBLReplicator_Internal.hh

* Implemented Replicator log heiroglyphics by using symbols to describe replicator.
* Implement desc() function to return a string describing Replicator, Database, and Endpoint.

CBL-5568 : Replicator log heiroglyphics

---

include/cbl/CBLDefaults.h
include/cbl/CBLIndexTypes.h
src/CBLCollection_Internal.hh
src/CBLDefaults_CAPI.cc
src/exports/CBLDefaults_EE_Exports.txt
src/exports/generated/CBL_EE.def
src/exports/generated/CBL_EE.exp
src/exports/generated/CBL_EE.gnu
src/exports/generated/CBL_EE_Android.gnu
test/VectorSearchTest.cc

* Added numProbes to the VectorIndexConfiguraiton.
* Change min/maxTrainingSize default value to 0.

CBL-5887 : Add numProbes and update training size default value

---

CBL_C.xcodeproj/project.pbxproj
include/cbl++/Collection.hh
include/cbl++/CouchbaseLite.hh
include/cbl++/Database.hh
include/cbl++/Document.hh
include/cbl++/Prediction.hh
include/cbl++/QueryIndex.hh
include/cbl++/VectorIndex.hh
include/cbl/CBLQueryIndex.h
include/cbl/CBLQueryIndexTypes.h
test/VectorSearchTest.hh
test/VectorSearchTest_Cpp.cpp

* Created C++ wrapper for the followings : VectorIndexConfiguration, QueryIndex, IndexUpdater, and Prediction.
* Added a sanity tests for the C++ wrapper.
* Updated some API docs.

CBL-5939 : Create C++ wrapper for vector index

---

include/cbl++/Database.hh
include/cbl/CBLCollection.h

Fix API doc per the fact that the default collection cannot be deleted.

CBL-5891 : Fix API doc regarding the default collection and scope

---

.github/workflows/build_android.yml
include/cbl++/Database.hh
include/cbl/CBLCollection.h

Fix API doc as the default collection cannot be deleted.

CBL-5982 : Fix API doc regarding the default collection and scope

---

CBL_C.xcodeproj/project.pbxproj
include/cbl/CBLCollection.h

* Updated LiteCore to 3.2.0-220.
* Minor API doc fix.
* Fixed xcode project file refering to the old test file name.

Update LiteCore to 3.2.0-220

---

include/cbl/CBLDatabase.h
src/CBLDatabase_Internal.hh
test/DatabaseTest.cc

* Implemented FullSync DatabaseConfiguration property.
* No change to C++ Public API as it uses C's CBLDatabaseConfiguration directory.
* Updated LiteCore to 3.1.9-5

CBL-6067 : Implement FullSync DatabaseConfiguration property

---

jenkins/linux-package-config.json

Updated linux-package-config so that the deb file for debian12 can be generated.

CBL-6196: Update linux-package-config to include debian12

---

include/cbl++/Collection.hh
include/cbl/CBLCollection.h
include/cbl/CBLQueryIndexTypes.h
src/CBLCollection_CAPI.cc
src/CBLCollection_Internal.hh

* Implemented Array Index API.
* C API for the expressions are different from the other platform as it’s just a string. This is inline with the ValueIndexConfiguration.
* Pending the complete implementation with LiteCore.

CBL-5178 : Implement Array Index API

---

jenkins/ci_cross_build.py
jenkins/cross_manifest.json

Now tested via toy build system and found to work correctly.

Fix the half done merge that went in for clang

---

include/cbl/CBLDatabase.h
include/cbl/CBL_Compat.h
src/CBLDatabase_Internal.hh
test/DatabaseTest.cc

* Added mmapDisabled to CBLDatabaseConfiguration. The config is not available on macOS platform.

CBL-6309 : Implement database disable mmap config

---

include/cbl/CBLTLSIdentity.h

Corrected and improved API doc for TLSIdentity.

Update TLSIdentity API Doc

---

include/cbl/CBLTLSIdentity.h
src/CBLTLSIdentity_CAPI.cc
src/exports/CBL_EE_Exports.txt
src/exports/generated/CBL_EE.def
src/exports/generated/CBL_EE.exp
src/exports/generated/CBL_EE.gnu
src/exports/generated/CBL_EE_Android.gnu

Change CBLCert_getValidTimespan to CBLCert_ValidTimespan for consistency.

Change CBLCert_getValidTimespan function name

---

include/cbl/CBLReplicator.h

* Grouped required fields (collections, collectionCount, endpoint) at the top for easier aggregate initialization using { }.
* Moved optional/core/common configuration fields (replicatorType, continuous, authenticator, context) below required fields to logically separate required vs optional settings.
* Rearranged TLS, auto purge, retry, WebSocket, HTTP, and advanced TLS settings into coherent sections for readability and maintainability.
* Goal: Make struct initialization more intuitive and improve discoverability of critical fields while keeping optional/advanced settings clearly separated.
* Note : This is a breaking change for existing code that uses aggregate initialization with { }. However, the new member order makes it much easier to initialize the struct with the required fields.

CBL-7399 : Restructure CBLReplicatorConfiguration member order
