- CBL_C.xcodeproj/project.pbxproj
* when building from xcode, CBL_C Framework target was failing due to the unknown , which was added by referencing in the linked frameworks and libraries.
> fix: build error

- python/CouchbaseLite/BuildPyCBL.py
These build-script changes have been tested on cmake, and the generated python bindings pass the tests in test.py on both linux and MacOS. 
The defaults for the build script should make it behave the same as before adding cmake support, to avoid breaking existing workflow for core devs, but this still needs to be tested by someone who actually uses xcode.
> Cross platform python

- src/CBLReplicatorConfig.hh
In CivetWebSocket.cc (couchbase-lite-core), the property is used to decide how to do the authentication :
```                
slice authType = auth[kC4ReplicatorAuthType].asString();
if (authType == slice(kC4AuthTypeBasic)) {
```
At the moment, any attempt to use basic auth fails with 401 Unsupported auth type.
> BasicAuthenticator needs to write the auth type in replication options

- bindings/python/BuildPyCBL.py
- src/CBLLog.cc
This PR fixes two items:
* compilation error caused by an uncasted nullptr
* Python binding error caused by Cdeclaration of functions that no longer exist.
> bugfix missing python bindings cdeclarations

- CBL_C.xcodeproj/xcshareddata/xcschemes/CBL_C Framework.xcscheme
- CBL_C.xcodeproj/xcshareddata/xcschemes/CBL_Tests.xcscheme
- CMakeLists.txt
- include/cbl/CBL_Compat.h
- jenkins/jenkins_unix.sh
- src/CBLReplicatorConfig.hh
Linking on Linux makes no sense to me, but apparently unless I instruct it to bring in the whole static library it will ignore important bits when linking a dynamic library and cause undefined references later.
Fixes #61
> Put LiteCoreStatic inside whole library flag

- bindings/nim/README.md
- bindings/nim/src/CouchbaseLite/private/cbl.nim
- bindings/nim/src/CouchbaseLite/private/fl.nim
This adds a conditional to select the correct name for the dynamic library based on platform. It has a switch for Windows as well, but this remains untested. Also updated the README to include how to run on Linux and explain why `nimble build` doesn't do anything (because it's a library package and not a binary package, `nimble install` would put the library in your nimble path so you could import it directly from your projects).
> Fix Nim bindings on Linux, and updated README

- cmake/platform_win.cmake
- include/cbl++/Database.hh
- include/cbl++/Replicator.hh
- src/exports/CBL.def
This commit solves the 
`LNK1104	cannot open file '${CB_PATH}/couchbase-forked/couchbase-lite-C/src/CBL.def'`
and the 
`LNK2001	unresolved external symbol CBL_SetLogLevel	CouchbaseLiteC	${CB_PATH}\couchbase-lite-C\build_cmake\CBL.def`
errors when building in VIsual Studio.
It adds CBLLog_SetConsoleLevel to the public interface and adds the required includes in the Replicator.hh and Database.hh files.
> Copy CBL.def to src, remove undefined CBL_SetLogLevel

- test/CMakeLists.txt
Removed FleeceStatic dependency and added required fleece source files (for all platforms and for windows) directly.
> CBL-1625: Fix test build fail on windows

- include/cbl++/Document.hh
- include/cbl/CBLDatabase.h
- include/cbl/CBLDocument.h
- src/CBLDatabase.cc
- src/CBLDatabase_Internal.hh
- src/CBLDocument.cc
- src/exports/CBL_Exports.txt
- src/exports/generated/CBL.def
- src/exports/generated/CBL.exp
- src/exports/generated/CBL.gnu
- src/exports/generated/CBL_EE.def
- src/exports/generated/CBL_EE.exp
- src/exports/generated/CBL_EE.gnu
- test/CBLTest.cc
- test/DatabaseTest.cc
- test/DatabaseTest_Cpp.cc
- Removed CBLDatabaseConfiguration.flags and used kC4DB_Create | kC4DB_VersionVectors by default.
- Renamed create object functions that use *New* to *Create*.
- Renamed CBLDocument_ToMutable to CBLDocument_MutableCopy.
- Renamed CBLDocument_ToJSON to CBLDocument_CreateJSON.
- Fixed cbl++/Document’s adopt() to return null when document is not found instead of throwing an exception.
- Fixed Save Empty Document to check RevID in non-version-vector format.
- Fixed C++ Batch With Exception Test.
- NOTE: This PR will be merged to dev branch.
> Apply API changes and fix test fails

- CMakeLists.txt
Added link with LiteCoreREST_Static for any calls to c4listener.
> Fix missing link with LiteCoreREST_Static

- .github/workflows/build.yml
* Problem : (1) running tests on Windows was hang as the tmp needs to be created before running the test (2) the path to `names_100.json` used in the test is not correct on Windows due to the path used to run the test.
* Fixed the running test path so that `names_100.json` can be accessed correctly on both Windows and others.
* Create tmp folder before running the test on Windows, otherwise the tests will be just hang.
> Fix GH Action Test Path

- cmake/platform_android.cmake
- cmake/platform_apple.cmake
- cmake/platform_linux.cmake
- cmake/platform_linux_desktop.cmake
- cmake/platform_win.cmake
- include/cbl/CBLDatabase.h
- src/CBLDatabase.cc
- src/CBLDatabase_Internal.hh
- test/DatabaseTest.cc
* Applied changes to Database Encryption API.
* Kept encryptionKey inside CBLDatabase for returning it back when calling CBLDatabase_Config.
* Added a test for testing database encryption.
* Fixed EE exported symbol file settings.
> Apply changes to Database Encryption API

- .gitignore
- CBL_C.xcodeproj/project.pbxproj
- CMakeLists.txt
- Xcode/generate_edition_header.sh
- Xcode/xcconfigs/Tests.xcconfig
- Xcode/xcconfigs/XCTests.xcconfig
- include/cbl/CBLBase.h
- include/cbl/CBL_Edition.h.in
- test/CMakeLists.txt
* This PR is to allow EE users to be able to use the APIs that are marked as EE APIs.
* Generated CBL_Edition.h which defines COUCHBASE_ENTERPRISE when building EE edition. The CBL_Edition.h file is generated from CBL_Edition.h.in. 
* Added generate_edition_header.sh script for generating CBL_Edition.h from XCode.
* In XCode project, added build phase for CBL_C and CBL_C Framework target to generate and copy CBL_Edition.h.
* In XCode project, added Xcode/generate_headers to the header search path of the test targets.
> Generate CBL_Edition.h

- include/cbl++/Database.hh
Fixed build error as "Database.hh:273:33: error: use of undeclared identifier kCBLLogDomainDatabase" by including CBLLog.h in Database.hh
> Fixed build failure as kCBLLogDomainDatabase is undeclared

- .github/workflows/applebuild.yml
- CBL_C.xcodeproj/project.pbxproj
- Xcode/CouchbaseLite.modulemap
- Xcode/mergeIntoStaticLib.sh
- scripts/build_apple.sh
* Added scripts/build_apple.sh for building xcframework. Use —ee option to build ee version.
* Fixed mergeIntoStaticLib.sh for the file paths including space.
* Made C++ headers project level depency so they will not be copied into the framework file.
* Fixed CouchbaseLite.modulemap and Removed C++ headers.
* Removed Fleece’s C++ headers files in Copy Fleece Header build pharse.
> Add a script for building xcframework

- include/cbl++/Replicator.hh
- include/cbl/CBLReplicator.h
- src/CBLReplicator_Internal.hh
- test/ReplicatorEETest.cc
- test/ReplicatorTest.cc
* Fixed CBLReplicationFilter signature to use CBLDocumentFlags instead of deleted boolean param.
* Added Push and Pull filter tests.
> Fix wrong signature in CBLReplicationFilter

- include/cbl++/Query.hh
- include/cbl/CBLQuery.h
- src/CBLQuery_Internal.hh
- test/QueryTest.cc
Synchronize when get and set the listener token in QueryTest class.
> Fix race condition in Query Listener Test

- CBL_C.xcodeproj/project.pbxproj
- Xcode/CouchbaseLite.modulemap
This involves also adding in a script during framework generation to search for self referencing includes and make sure they are in the format <CouchbaseLite/[header].h> because if they are in quotes, then the compiler is angry, but if they are in brackets then the compiler is angry unless the prefix is there
> Flatten CBL-C framework headers

- include/cbl++/Query.hh
- test/QueryTest.cc
This is the motivation of the change. Currently, we add listener as follows,
ChangeListener listener = addChangeListener(callback), where the callback gets called when the change takes place, and then we can get the change from "listener," as listener.result(). One place to handle the change is inside the callback. However, before "addChangeListener" is returned, listener is incomplete. This actually caused crashing due to the race condition, whereby the callback is something like "callback = [](){ listener.results();}"
Whereas this use itself is bug, which can be fixed by, inside the callback, waiting for the add function to return. However, we want to improve the API to be less liable to that kind of error. After discussing with Pasin, we derived this solution of this PR. We provide the …
> Feature/cbl c/cbl 1783

- include/cbl++/Replicator.hh
- include/cbl/CBLReplicator.h
- src/CBLReplicatorConfig.hh
Added disableAutoPurge property to the CBLReplicatorConfiguration. Per discussion in the API spec, CBL-C will have a negative property to allow the default value as false, while the other platforms including c++ binding will have enableAutoPurge property.
> CBL-1970 : Implement disableAutoPurge config

- src/CBLDatabase+Apple.mm
It's possible the Application Support Directory might not exist. So attempt to create the default directory if the path doesn't exist.
> CBL-2092: Create default directory if it doesn’t exist (Apple Only)

- src/Internal.cc
Use a static variable for global initializing that calls enablingFatalExceptionBacktrace().
> Add initializer to call enablingFatalExceptionBacktrace()

- src/CBLDatabase_Internal.hh
- test/DatabaseTest.cc
We will not support Version Vector in Lithium so disable version vector when creating the database.
> Disable Version Vector

- include/cbl/CBLDocument.h
- src/CBLDatabase_CAPI.cc
- src/CBLDocument_Internal.hh
- test/DatabaseTest.cc
* Added Database and Document tests.
* Fixed CBLDatabase_SaveDocumentWithConflictHandler’s conflictHandler from nullable to non-null
* Validated database matching in CBLDatabase_PurgeDocument.
* Improved code coverage (both lines and functions) about 3% (line 68.3%, function 79.4%)
> Add Database and Document tests

- src/CBLLog.cc
Use default MaxSize is 500K and MaxRotateCount is 1 when the configured value is zero.
> Apply platform default value for LogFileConfig’s MaxSize and MaxRotateCount

- test/QueryTest.cc
Remove listener token and sleep to ensure async cleanup and free in LiteCore's LiveQuerier's _stop() functions is done before checking instance leaking in CBLTest's destructor.
> Remove token and put small sleep in Query Listener Test

- CBL_C.xcodeproj/xcshareddata/xcschemes/CBL_C Dylib.xcscheme
- CBL_C.xcodeproj/xcshareddata/xcschemes/CBL_C.xcscheme
- CMakeLists.txt
- README.md
- Xcode/xcconfigs/CBL_static.xcconfig
- bindings/nim/README.md
- bindings/nim/src/CouchbaseLite/private/cbl.nim
- bindings/nim/src/CouchbaseLite/private/fl.nim
- bindings/python/BuildPyCBL.py
- bindings/rust/CouchbaseLite/build.rs
- cblite.pc.in
- cmake/CouchbaseLiteConfig.cmake.in
- cmake/cblite.rc.in
- cmake/platform_android.cmake
- cmake/platform_apple.cmake
- cmake/platform_linux.cmake
- cmake/platform_linux_desktop.cmake
- cmake/platform_win.cmake
- jenkins/server_build_unix.sh
- jenkins/server_cross_unix.sh
- scripts/coverage.sh
- test/CMakeLists.txt
The new library names and details are as follows:
Windows:
cblite-static.lib (static library, no version info)
cblite.dll (dynamic library, version info inserted via RC file [see cblite.rc.in])
macOS:
libcblite-static.a (static library, no version info)
libcblite.3.0.0.dylib (dynamic library, compatibility version set to 3.0.0 current version set to 3.0.0)
libcblite.3.dylib (compatibility version driven symlink to actual file)
libcblite.dylib (rolling symlink to any target)
Linux:
libcblite-static.a (static library, no version info)
libcblite.so.3.0.0 (dynamic library actual file)
libcblite.so.3 (SOVERSION driven symlink to actual file)
libcblite.so (master symlink to any version)
> CBL-2083: Change to official library name and version

- CMakeLists.txt
- scripts/coverage.sh
- test/CMakeLists.txt
* Updated coverage.sh to filter all vendors out.
* Update test’s CMakeLists.txt to include ReplicatorEETest.cc.
* Update main’s CMakeList.txt to print the edition (EE or CE) info.
> Update code coverage script and CMakeList.txt

- src/CBLReplicator_Internal.hh
- test/ReplicatorEETest.cc
- test/ReplicatorTest.cc
- test/ReplicatorTest.hh
* The root cause of CBL-2162 is that when there are no changes to replicate, the replicator is stopped or idle with status.progress.complete = 0.0 instead of 1.0.
* Returns a initial status which has complete status = 0.0 if the replicator hasn’t ever been started.
* Returns complete status = 1.0 if the replicator is stopped or idle but having no changes to replicate.
* Added and updated tests
> CBL-2162 : Fix Replicator’s complete progress when having no changes to replicate

- src/CBLReplicator_Internal.hh
From CBL-2162, it's possible that the unitsCompleted could be more than unitsTotal. To workaround the problem and return the correct range of value (0.0 - 1.0), when computing the fractional complete, return 1.0 if unitsCompleted is more than unitsTotal.
> CBL-2162 : Workaround for handling unitsCompleted more than unitsTotal

- src/CBLDocument.cc
- src/CBLDocument_Internal.hh
- src/ConflictResolver.cc
- test/ReplicatorEETest.cc
- test/ReplicatorTest.hh
* Made that the remote branch will always win so that the saved resolved doc will not be conflicted when it is being push to the remote server.
* In ConflictResolver::customResolve(conflict), renamed otherDoc to remoteDoc and myDoc to localDoc to match the actual term.
* In ConflictResolver::customResolve(conflict), fixed retained count when the resolved doc is the same as local or remote doc.
* Updated Lite Core to pick up the fix in purgeRevision after resolveConflict (c25026c).
* Added tests
> CBL-2160 : Fix local win doc not being push to the server

- CBL_C.xcodeproj/project.pbxproj
- include/cbl++/Base.hh
- include/cbl/CBLLog.h
- src/CBLLog.cc
- src/CBLPrivate.h
- src/exports/CBL_Exports.txt
- src/exports/generated/CBL.def
- src/exports/generated/CBL.exp
- src/exports/generated/CBL.gnu
- src/exports/generated/CBL_EE.def
- src/exports/generated/CBL_EE.exp
- src/exports/generated/CBL_EE.gnu
- test/CMakeLists.txt
- test/LogTest.cc
- Initialize the global log level of each specific domain to debug so logging can be further limited by the levels assigned to the current callback and/or binary file.
- Removed CBLLog_ConsoleLevelOfDomain and CBLLog_SetConsoleLevelOfDomain.
- Allowed both console and custom log working at the same time if both are enabled.
- Fixed CBL-2175 : Setting verbose log doesn’t work
- Fixed CBL-2188 : CBL_LogMessage() not logging to callback
- Fixed CBL-2181 : Parameter of CBLLog_SetCallback not marked as nullable
> Reimplement CBLLog

- src/CBLDocument.cc
- src/CBLDocument_Internal.hh
- test/CMakeLists.txt
- test/DatabaseTest.cc
* Not lock the document while saving the document. This is inline with the implementation on the other platform. I have created CBL-2200 (post lithium) to prevent concurrent save/delete/purge on the same doc object.
* Call conflict handler outside database lock.
* Add more tests.
> CBL-2187 : Fix deadlock when using doc or db in conflict handler running in different thread

- CMakeLists.txt
- include/cbl++/Replicator.hh
Not sure if the C++ headers not being installed was meant to be there - can't see why it would be. A `/usr/local/` install now works as expected for me. 
But mainly the fix ensures that string views of zero length strings are not used inadvertently.
> Fix empty server certs being loaded. Adds C++ header installation

- include/cbl/CBLReplicator.h
- src/CBLDocument.cc
- src/CBLDocument_Internal.hh
- test/ReplicatorEETest.cc
* Modified tests Custom resolver to test blobs in resolved doc. Found that during encoding the resolved doc body to save, the kHasAttachments flag has already been set properly if the doc contains blobs (CBL-2190).
* However found an issue that the new blobs set in the resolved doc need to be released but only after they are installed into the database. So fix the issue to allow the new blobs to be released and update the API comment of the conflict resolver callback that blobs need to be retained when returning the resolved doc.
> Release new blobs set in doc returned by conflict resolver

- CMakeLists.txt
- cmake/generate_edition.cmake
- include/cbl/CBL_Edition.h.in
This will be scooped up as part of the main CMake configuration, but also it can be run in standalone by invoking CMake in script processing mode such as the following:
`cmake -DVERSION="3.0.0" -DOUTPUT_DIR="$pwd" -DBLD_NUM=67 -DBUILD_ENTERPRISE=ON -P ..\cmake\generate_edition.cmake`
This means it can be used in the Xcode build as well
> Create a cmake script to generate dynamic build information

- src/CBLDocument.cc
- test/DatabaseTest.cc
Registered new blob using digest (slice) instead of blob properties (FLDict) so that the registered blob could be found when setting indirect blob properties into the document.
Note: slice is a subclass of pure_slice which implements hash function and == operator based on the slice's content.
> CBL-2202 : Register new blob using digest

- CBL_C.xcodeproj/project.pbxproj
- CMakeLists.txt
- src/CBLDatabase_Internal.hh
- src/CBLQuery.cc
- src/CBLQuery_Internal.hh
- src/CBLReplicator_Internal.hh
- src/Internal.hh
- test/DatabaseTest.cc
Implemented the logic to allow to register and unregister stoppable objects (Replicators and Query Listener Tokens) to the database so that the database can calls to stop when it is being closed or deleted.
CBL-2135 and CBL-2221
> Stop Replicators and Live Queries when closing or deleting database

- CBL_C.xcodeproj/project.pbxproj
- Xcode/xcconfigs/Tests.xcconfig
- Xcode/xcconfigs/XCTests.xcconfig
- include/cbl++/Base.hh
- include/cbl++/Blob.hh
- include/cbl/CBLBlob.h
- src/CBLBlob_Internal.hh
- src/CBLDatabase.cc
- src/CBLDatabase_Internal.hh
- src/CBLDocument.cc
- src/CBLDocument_Internal.hh
- src/CBLPrivate.h
- src/CBLQuery.cc
- src/CBLQuery_CAPI.cc
- src/CBLQuery_Internal.hh
- test/BlobTest_Cpp.cc
- test/CBLTest_Cpp.hh
- test/DatabaseTest.cc
- test/QueryTest.cc
Using new Fleece API `FLDoc_SetAssociated` (https://github.com/couchbaselabs/fleece/pull/109) to associate a CBLQuery with the Fleece data of a query result set. This then allows CBLBlob to discover when a Value belongs to such a result set, and create a CBLBlob on it.
Other changes:
* Added some missing `_cbl_nullable` annotations; this was triggering the
Clang UB Sanitizer during tests.
* CBLQuery_Internal.hh still had some `using namespace` declarations, which
we've decided we don't want in headers, so I removed them. This then meant
I had to add some missing `std::` and `fleece::` prefixes in other headers
that now became syntax errors.
* I had to move several CBLResultSet methods from the header to the .cc file,
because they use CBLBlob but the header can't include …
> @snej Make FLDict_GetBlob work in query results (CBL-2269)

- cmake/platform_win.cmake
- include/cbl/CBLBlob.h
- include/cbl/CBLReplicator.h
- include/cbl/CBL_Compat.h
- src/CBLBlob_CAPI.cc
- src/CBLLog.cc
- src/ConflictResolver.cc
Note: choosing CBL_PUBLIC instead of CBL_API because of the already similarly named CBLAPI a few lines below.
> CBL-2253: Change CBL_CORE_API to CBL_PUBLIC and add explanation

- src/CBLDatabase_Internal.hh
- test/DatabaseTest.cc
Catch BadDocID and log warning instead of throwing to match this specific behavior with the other platform.
> Catch BadDocID and log warning instead of throwing

- src/ConflictResolver.cc
Before, if a conflict resolution resulted in no work it was skipped which would never allow the replicator to exit busy status.
> CBL-2307: Always call the completion handler of the conflict resolver

- src/CBLReplicator_Internal.hh
- test/ReplicatorEETest.cc
- test/ReplicatorTest.cc
- test/ReplicatorTest.hh
* Instead of using configuration to progress level for document replication listeners, used setProgressLevel.
* Added OnEmptyCallback callback to the (Private) ListenersBase and Listeners class.
* Removed extra calls to encodeOptions as it is not needed anymore.
CBL-2337
> Use setProgressLevel and remove extra encodeOptions

- src/CBLReplicatorConfig.hh
- test/ReplicatorTest.cc
* Copied endpoint and authenticator in ReplicatorConfiguration copy constructor.
* Added virtual clone function to CBLEndpoint and CBLAuthenticator that their subclasses will impelement.
CBL-2347
> Copy endpoint and authenticator config

- Xcode/CouchbaseLite.modulemap
Added CBLEncryptable.h and CBLPlatform.h to CouchbaseLite.modulemap.
CBL-2361
> Add missing headers in modulemap file

- src/CBLDocument.cc
- src/CBLDocument_Internal.hh
- test/ReplicatorPropEncTest.cc
* We do not support encryptables in arrays.
* (EE Only) Extended the saveBlobs function (called ) that walks the properties tree to find and install blobs to also validate the encryptables in arrays. For CE, the method will work the same way.
* When checking encryptables in arrays, it needs to also look into the immutable collections in the document properties as well because, for an example, the document can be set with JSON which will result to a shallow mutable properties.
CBL-2265
> Validate encryptable in arrays when saving doc

- include/cbl++/Blob.hh
- include/cbl/CBLBlob.h
- test/BlobTest.cc
- test/BlobTest_Cpp.cc
- test/DatabaseTest.cc
Added three inline convenience functions that wrap FLSlot_SetBlob, matching the
ones recently added to Fleece.h for the other data types.
I removed the doc-comment from FLSlot_SetBlob, to make it less prominent in the
API docs, and avoid confusing users.
In the C++ API I added an implicit conversion from Blob to Dict, so that Blob
can be assigned to a Dict or Array item, e.g. `dict["foo"] = blob`.
(Since this is an API change, Pasin's got final approval.)
> API: Added blob setters: FLMutableDict_SetBlob + 2 more

- src/CBLReplicatorConfig.hh
The statement `endpoint = endpoint ? endpoint->clone() : nullptr` triggers an
Undefined Behavior Sanitizer warning/breakpoint when `endpoint` is NULL,
because it stores NULL into a pointer declared as `_cbl_nonnull`. This occurs
during the "Bad config" unit test.
I made a simple fix to avoid storing anything into it when it's NULL.
> Avoid UB-Sanitizer warning in CBLReplicatorConfig

- test/DatabaseTest.cc
- test/ReplicatorEETest.cc
* Added a test to confirm that the mutable properties properly retained after setting to a doc.
* Updated merge conflict resolution test to create a new merged doc, set properties from the local doc, and set value from remote doc.
CBL-2303
> Add tests checking if mutable props is properly retained

- jenkins/ci_build_android.sh
It will happen anyway when building an app, and this way the distributed file can be upload to crash reporting services for proper symbolication
> Disable Android library stripping

- src/CBLDatabase.cc
- test/DatabaseTest.cc
Retain database in the ListenerToken<CBLDocumentChangeListener> to allow to remove / release the token after closing and releasing the database (using CBLDatabase_Release). On the binding platform that uses GC, the order of releasing the object is not guaranteed so the database might be released before the token.
> CBL-2548 : Retain database in ListenerToken of CBLDocumentChangeListener

- CMakeLists.txt
Failure message when attempting to build as non-root user on Linux
CMake Error: Could not open file for write in copy operation /usr/local/lib/x86_64-linux-gnu/cmake/CouchbaseLite/CouchbaseLiteConfigVersion.cmake.tmp
CMake Error: : System Error: No such file or directory
CMake Error at cmake-3.11/Modules/WriteBasicConfigVersionFile.cmake:46 (configure_file):
configure_file Problem configuring file
Call Stack (most recent call first):
cmake-3.11/Modules/CMakePackageConfigHelpers.cmake:209 (write_basic_config_version_file)
CMakeLists.txt:226 (write_basic_package_version_file)
write_basic_package_version_file() should not be told to write
directly to the system libdir. This gets called during configuration,
when the build should not be trying to write to any system directories.
Instead write …
> Fix cmake configuration failure on Linux

- src/Internal.cc
Set to CBLInitContext.tempDir instead of filesDir.
> CBL-2609 : Fix setting SQLite temp dir for Android

- include/cbl/CBLBlob.h
- src/CBLBlob_CAPI.cc
- src/CBLBlob_Internal.hh
- src/exports/CBL_Exports.txt
- src/exports/generated/CBL.def
- src/exports/generated/CBL.exp
- src/exports/generated/CBL.gnu
- src/exports/generated/CBL_Android.gnu
- src/exports/generated/CBL_EE.def
- src/exports/generated/CBL_EE.exp
- src/exports/generated/CBL_EE.gnu
- src/exports/generated/CBL_EE_Android.gnu
- test/BlobTest.cc
This looks like an accidental omission from the API. Other platforms' read streams support seeking.
I imagine this will require some API review... I've based the API on `fseek` and `ftell`.
Strictly speaking, `CBLBlobReader_Position` is unnecessary because you can either ask the blob itself, or you can call `CBLBlobReader_Seek(reader, 0, kCBLSeekModeRelative, nullptr)` which will return the current position.
CBL-2573
> API: Added `CBLBlobReader_Seek`, `CBLBlobReader_Position` (CBL-2573)

- include/cbl++/Database.hh
- include/cbl++/Document.hh
- include/cbl++/Query.hh
- include/cbl++/Replicator.hh
- test/DatabaseTest_Cpp.cc
- test/QueryTest.cc
* Minimum changes to C++ API to match the other platforms’ API.
* Renamed Database::SaveConflictHandler class to ConflictHandler
* Renamed Database::purgeDocumentByID() to purgeDocument()
* Renamed Database::Listener to ChangeListener and DocumentListener to DocumentChangeListener
* Added Database:: createQuery()
* Added Result::count() and toJSON()
* Made Authenticator and Endpoint class RefCounted
* Renamed Replicator::DocumentListener to DocumentReplicationListener
* Note: Created CBL-2724, CBL-2725, and CBL-2726 for additional bug fixes and improvement.
> Minor change to C++ API to match the other platforms

- CMakeLists.txt
- README.md
* (CBL-2394) Add STRIP_SYMBOLS option in CMakeLists.txt for generating debug symbol files and stripping private symbols from the built shared library (For macOS and linux only). This option is disabled by default so it will not impact the current build system.
* Update the build steps in the README file and include the info about using CMAKE_INSTALL_PREFIX to specify the install location (CBL-2400) in the build steps.
> CBL-2394 and CBL-2400 : Add STRIP_SYMBOLS options to cmake and update README

- CBL_C.xcodeproj/project.pbxproj
- CMakeLists.txt
- README.md
- include/cbl++/Base.hh
- include/cbl++/Blob.hh
- include/cbl++/CouchbaseLite.hh
- include/cbl++/Database.hh
- include/cbl++/Document.hh
- include/cbl++/Query.hh
- include/cbl++/Replicator.hh
* Marked CBL C++ API as volatile. 
* Copied CBL C++ and fleece C++ headers to the release package built by CMake
* Modified XCode Project to include CBL C++ and fleece C++ headers in the framework bundle
* Updated README about the volatile status of CBL C++ API
* NOTE: 
1. Fleece C++ API was not marked as Volatile.
2. I have experimented with #pragma message("") to add warning message about Volatile API at the header level. The result was pretty annoying as the warning messages will be shown every single time that the header is included during the build (probably in IDE as well). So I decided not to do that in this PR unless we think it's necessary.
> Mark C++ API as volatile and include them in release package

- cmake/platform_linux_desktop.cmake
This will allow a reduction in the number of unique builds needed for platform coverage.  Basically, at this point only two unique builds will be needed -> Builds for distros that are built against GCC 8+ and those that are not
> CBL-2775: Enable ICU shim for Linux builds

- include/cbl++/Replicator.hh
There is a change to constructor of the ReplicatorConfiguration to take the endpoint, but the Endpoint doesn’t handle copy properly so the underling CBLEndpoint object could get freed when while the Endpoint object is still in-used. Revert the change for now and will make a proper change all together including C++ tests. 
#227
> Revert change in C++ ReplicatorConfiguration

- src/CBLCollection.cc
- src/CBLCollection_Internal.hh
- src/CBLDatabase.cc
- src/CBLDatabase_Internal.hh
- src/CBLDocument.cc
- src/Listener.hh
- test/CollectionTest.cc
* Previously, in order to lock, CBLCollection calls database() to get the database pointer then calls useLocked() using the database pointer. Even though we have put some code to check if the database pointer is NULL or if the collection itself is valid in the database() function, the process to lock is not entirely safe as the moment from getting the returned database pointer and calling the useLocked() are not part of any lock and the database pointer could be freed during that time.
* This commit solves the above problem by making the CBLDatabase’s c4db access_lock a shared_ptr which will be shared with CBLCollection. This means that there will be no call to database pointer to lock anymore. As a bonus, when the shared_ptr of the c4db_access lock could be retained inside the …
> CBL-3184 : Improve access lock in CBLCollection

- include/cbl/CBLCollection.h
- include/cbl/CBLScope.h
- src/CBLCollection_CAPI.cc
- src/CBLDatabase.cc
- src/CBLDatabase_CAPI.cc
- src/CBLDatabase_Internal.hh
- src/CBLScope_CAPI.cc
- src/CBLScope_Internal.hh
- test/CollectionTest.cc
* Updated the API based on the updated on 20220601.
* Added more collection tests to test the behavior when database is closed or deleted.
* Simply implemented checking whether database is closed and throwing exception. This will be enhanced by using the database’s access lock in CBL-3231 to avoid large PR.
> CBL-3233 : Update Scope and Collection API

- include/cbl/CBLDatabase.h
- src/CBLDatabase.cc
- src/CBLDatabase_CAPI.cc
- src/CBLDatabase_Internal.hh
- test/CBLTest.cc
- test/CBLTest.hh
- test/CollectionTest.cc
- test/DatabaseTest.cc
* Implemented C4DatabaseAccessLock which has a uselocked’s sentry to throw a NotOpen error if is was closed.
* Updated the Database’s close and delete logic to close the scopes and collections (invalidate the database pointer) right away.
* The C4DatabaseAccessLock’s useLockedIgnoredWhenClosed() is used by CBLDatabase’s destructor to ignore the closed logic and throwing NotOpen exception if the database has already been closed. This would allow to have having to disable breaking point from exception in many places that release the database in tests.
* CBL-3232 : Added tests to test the behavior when using the Database APIs on the closed or deleted database and fixed bugs.
> CBL-3231 : Implement C4DatabaseAccessLock

- include/cbl/CBLCollection.h
- include/cbl/CBLDatabase.h
- include/cbl/CBLDocument.h
- include/cbl/CBLQuery.h
- include/cbl/CBLReplicator.h
- include/cbl/CBL_Compat.h
* Deprecated pre-collection APIs that use default collection.
* Use @warning in the API comment for the deprecation instead of deprecation attribute.
* The decision to use @warning for deprecation to avoid the deprecation warning error when #include CBLReplicator.h which contain deprecation on structs’ members in the source code. This problem was found at least when using clang on XCode.
> CBL-3187 : Deprecate pre-collection APIs

- CBL_C.xcodeproj/project.pbxproj
- CMakeLists.txt
- include/cbl/CBLCollection.h
- include/cbl/CBLScope.h
- src/CBLCollection_CAPI.cc
- src/CBLDatabase.cc
- src/CBLDatabase_CAPI.cc
- src/CBLDatabase_Internal.hh
- src/CBLReplicator_Internal.hh
- src/CBLScope.cc
- src/CBLScope_CAPI.cc
- src/CBLScope_Internal.hh
- test/CollectionTest.cc
* To make the API consistent with the others, the returned scopes and collections from the database will have RefCount + 1. This means that users will need to release it after they are done using it. This also means that if the collection is deleted from the database or the database is closed or released, the collection pointer (also scope pointer) will remain valid until it is being released.
* Noted that as the scope returned by CBLCollection_Scope() is a property of the collection, its lifetime will depend on the lifetime of the collection object.  If the object needs to be kept longer than the collection, users will need to explicitly retained.
* Updated the tests accordingly.
* Updated the API doc accordingly.
> CBL-3250 : Make returned Scope and Collection RefCount + 1

- CBL_C.xcodeproj/project.pbxproj
* Fixed missing target memberships in CBLScope.h
* Synced target memberships of all public headers to be the same.
> CBL-3318 : Fix XCode public header targets

- src/CBLCollection_Internal.hh
- src/CBLDatabase.cc
- test/CollectionTest.cc
* Update the code to use c4col’s isValid() check instead of c4db’s hasCollection() when checking if the cached collection is valid or not.
* For the implementation, make CBLCollection’s isValid() noexcept so it returns false when the collection is invalid isntead of throwing an exception. This requires some changes in C4CollectionAccessLock to not use the sentry.
* Enabled failed tests as the issues were fixed in LiteCore (CBL-3412 and CBL-3196)
> CBL-3328 : Use c4col's isValid() instead of c4db's hasCollection()

- jenkins/ci_build_android.sh
- jenkins/ci_build_ios.sh
- jenkins/ci_build_unix.sh
- jenkins/ci_build_win_desktop.ps1
- jenkins/ci_cross_build.py
notices.txt is generated by blackduck, contains component license information.  Per CBD-4471, we want to include it in couchbase-lite-c packages.
-Ming Ho
> CBD-4471, add notices.txt to couchbase-lite-c packages

- src/CBLCollection_Internal.hh
- src/CBLDatabase.cc
- src/CBLDatabase_Internal.hh
- src/CBLScope_Internal.hh
- test/CollectionTest.cc
* This PR fixed two issues, CBL-3304 and CBL-3317, at the same time as the fix of both issues are done at the same or related location in the code.
* [CBL-3304] When a collection is removed from the cache as the collection was deleted, the close() call on the collection is needed to invalidate its database pointer. Otherwise, the collection could have a dangle database pointer when the database is laster released.
* [CBL-3304] Similarly thing needs to be done on the scope. When a scope is removed from the cache as there are no collections in the scope anymore, the scope should be called to detach (not close) from the database. When the scope is detached, the scope will start to retain the database so that the scope can be continually used as normal and will not have the situation that the …
> Close collection or detach scope and handle NULL scope cases

- include/cbl/CBLReplicator.h
- src/CBLCollection_Internal.hh
- src/CBLReplicatorConfig.hh
- src/CBLReplicator_Internal.hh
- src/ConflictResolver.cc
- src/ConflictResolver.hh
* Made database and collections in CBLReplicatorConfiguration nullable. The config will be validated in the Replicator's constructor as both cannot be NULL.
* Copied CBLReplicatorConfiguration’s collections and retained each collections inside.
* Setup C4ReplicationCollection(s) from CBLReplicatorConfiguration’s collections. If the CBLReplicatorConfiguration’s database is used, create a C4ReplicationCollection with the default collection, outer filters, and outer conflict resolver. There are TODO marks that will need to be done when the collection support have been implemented in LiteCore's Replicator. Now, only the default collection via CBLReplicatorConfiguration’s database is supported.
* Made changes to ConflictResolver classes to use collection instead of database.
* Still throw …
> CBL-3191 : Setup C4ReplicationCollection(s) for CBLReplicatorConfiguration

- include/cbl/CBLReplicator.h
- src/CBLCollection_Internal.hh
- src/CBLReplicatorConfig.hh
- src/CBLReplicator_CAPI.cc
- src/CBLReplicator_Internal.hh
- src/ConflictResolver.cc
* Updated LiteCore to [92b21fd](https://github.com/couchbase/couchbase-lite-core/commit/92b21fdbac70ffe8e91833616874d34a9a3898f7).
* Enable collection support in replicator.
* Implemented CBLReplicator_PendingDocumentIDs2 and CBLReplicator_IsDocumentPending2.
* In both filter and conflict resolver, ensure to check the collection spec against the collections in the config. This is for avoid ing unexpected bugs.
* Fixed missing collection info in ReplicatedDocument event after resolving conflicts.
* Fixed property encryption bug that doesn’t use config’s documentPropertyEncryptor and _conf.documentPropertyDecryptor.
* Do not allow to use outer level filters & conflict resolver if database is not set. NOTE: This is different from the other platforms as CBLReplicatorConfiguration is just a …
> Update LiteCore, enable Collections support in Replicator and bugs fixes

- src/CBLCollection_Internal.hh
- test/DocumentTest.cc
* Threw NotFound error when setting expiraton fail. This follows the same implementation of c4coll_setDocExpiration() in LiteCore.
* Enabled previously failed tests due to CBL-3306 as the issue has been fixed.
> CBL-3590 : Fix Set Doc Expiration on Non Existing Doc

- src/CBLCollection_CAPI.cc
- test/CollectionTest.cc
Caught exception and returnning -1 instead of 0.
> CBL-3600 : Fix GetDocumentExpiration not return -1 for errors

- test/CollectionTest.cc
- test/DatabaseTest.cc
- test/DocumentTest.cc
* Enabled failed tests that have been fixed (CBL-3183 and CBL-3195)
* Made Close / Delete Database with Active Replicator less flaky from `Assertion failed: _driver && _driver->_peer` error.
* Removed "Get Non Existing Document" in DocumentTest.cc as duplicated.
* Renamed some tests in DocumentTest.cc
> Enable disabled tests

- include/cbl++/Collection.hh
- include/cbl++/Document.hh
- test/DocumentTest_Cpp.cc
* Added Document’s collection() to the C++ API.
* Updated tests.
> CBL-3650 : Add Document’s collection() to C++ API

- CBL_C.xcodeproj/project.pbxproj
- include/cbl++/Base.hh
- include/cbl++/Collection.hh
- include/cbl++/Replicator.hh
- test/CBLTest.cc
- test/CBLTest_Cpp.hh
- test/CMakeLists.txt
- test/ReplicatorCollectionTest_Cpp.cc
* Updated ReplicatorConfiguration class to have two constructors that accepts `Database`/`Endpoint` and `vector<ReplicationCollection>`/`Endpoint`. The database, endpoint, and vector of `ReplicationCollection` object will be immutable after the `ReplicatorConfiguration` is created.
* Made `Endpoint` and `Authenticator` class correctly copyable by keeping the C’s `ref` pointer in `shared_ptr.` This (especially for the `Endpoint`) is required otherwise the Endpoint object cannot be passed to the constructor of  the `ReplicatorConfiguration` class.
* When setting the C’s CBLReplicatorConfiguration’s context in the Replicator class, instead of using 'this' which is the Replicator object, use the new collection map which is a pointer to an `unordered_map<Collection, ReplicationCollection>` …
> CBL-3588 : C++ API - Support collections in replicator

- src/CBLDatabase.cc
- src/CBLDocument_CAPI.cc
Added exception handlers to CBLEncryptionKey_FromPassword and CBLEncryptionKey_FromPasswordOld per FIXME tag.
> CBL-3685 : Fix missing exception handler

- include/cbl++/Replicator.hh
- test/ReplicatorCollectionTest_Cpp.cc
Change the Endpoint and Authenticator API to use static functions to create the object. This will also make the created Endpoint/Authenticator object immutable.
> CBL-2726 : Change the Endpoint and Authenticator Cpp API

- include/cbl++/Database.hh
- include/cbl/CBLDatabase.h
- src/CBLDatabase_Internal.hh
- src/Listener.hh
* Created NotificationsReadyCallbackAccess class for keeping and calling the callback function thread safely.
* Instead of simply creating and using NotificationsReadyCallback pointer which is leaking, use a share pointer of NotificationsReadyCallbackAccess to the Database class so that it can shared among the copied of the Database objects and can be freed when all copied of the Database objects are gone.
> CBL-3685 : Fix pointer leak in CPP's bufferNotifications()

- test/QueryTest.cc
- test/ReplicatorPropEncTest.cc
- test/ReplicatorTest.hh
* Updated LiteCore to 3.1.0-249
* Update QueryTest’s tests that check explain string as the format has been changed by SQLite.
* Bump async replicator clean up delay to 500ms to avoid flakey failure when checking instance leaks.
* Removed verbose log enabled for debugging from a ReplicatorPropertyEncryptionTest’s test.
> Update LiteCore to 3.1.0-249

- include/cbl++/Replicator.hh
- src/CBLReplicator_CAPI.cc
- test/ReplicatorCollectionTest.cc
- test/ReplicatorCollectionTest_Cpp.cc
* Added more C++ Replicator Tests
* Fixed bug that an empty dict should be returned when there is no pending doc ids instead of NULL.
* Fixed crash from returned released pending doc ids dictionary.
> CBL-2783 : Add more C++ Replicator Tests and Fix bug

- jenkins/CMakeLists.txt
Removing the need to download ICU, since it uses the system one
> Add CMakeLists for build server

- include/cbl++/Query.hh
- test/QueryTest.cc
* As part of investigating CBL-2815 issue reported by the user that the `Query::ChangeListener`, a subclass of `ListenerToken` class, is not moveable, I have found that the example given by the user is not working as well because the Query::ChangeListener can not pre-declared as a class member as it doesn’t have the defualt constructor explictly defined.
* This basically makes the `Query::ChangeListener` different from the other listeners such as CollectionChangeListener, which is a direct type of the `ListenerToken` class which does have a default constructor.
* This commit basically adds a default constructor the Query::ChangeListener. Also, for an empy or null QueryListener, do not allow to call results() by throwing a runtime exception as there is no query and token object to use.
> CBL-2815 : Add default constructor to Query::ChangeListener

- src/CBLCollection.cc
- src/CBLQuery_Internal.hh
- src/Listener.cc
- src/Listener.hh
Before this change it was possible that a callback was executing even after the call to remove a listener has returned.
This is a problem if the callback context is immediately destroyed after the listener has been removed. The callback might continue to access the now invalid context.
> Wait for listener callbacks to finish when removing listener

- CBL_C.xcodeproj/project.pbxproj
- Xcode/xcconfigs/XCTests.xcconfig
* Added Generate Header Build phrase script to CouchbaseLiteTests target so that it can be built and run.
* Note: CouchbaseLiteTests target allows to run Catch2 tests as an XCTest test on macOS. This is very useful for using XCode to profile tests.
> Fix XCode CouchbaseLiteTests target

- src/Listener.hh
Added _cbl_nullable to the _callback as it could be null (e.g. after the token is removed).
> Fix nullable warning in CBLListenerToken

- src/CBLDocument_Internal.hh
- src/CBLReplicator_Internal.hh
- src/ConflictResolver.cc
- src/ConflictResolver.hh
- test/ReplicatorEETest.cc
* Port fix from the master branch (b8f77dde64b241399fc3fa0f2cc89d4ebf8f3771) (Original issue CBL-3609) for 3.0.6-MR.
* Changed the conflict detection and conflict revision to be the same as the logic in the other platforms so that the code doesn’t use inaccurate revision flags and revID from the DocumentEnded (CBL-3610).
* With the new logic, no needs to pass revID from DocumentEnded to ConflictResolver class so removing _revID from the class.
* Fixed a bug in ConflictResolver::runNow() that doesn’t reset inConflict to false when resolving is successful.
* Fixed bugs in CBLDocument that doesn’t use revID and sequence from selected revision (e.g. when conflicting revision is selected).
* Added Test
> CBL-3611 : Fix pending conflicts are not being called to resolve (Port)

- src/CBLDatabase.cc
- src/CBLQuery_Internal.hh
- src/Listener.cc
- src/Listener.hh
* Port fix from the master branch (https://github.com/couchbase/couchbase-lite-C/commit/15eb54a93664915e6c400f55528021bed0213c44) for 3.0.6-MR.
* Wait for listener callbacks to finish when removing listener
* Use `recursive_mutex` to lock in CBLListenerToken's removed() and in ListenerToken's call(). 
* In ListenerToken's call(), allow to call the callback under the recursive lock as the lock is not shared and is only per a ListenerToken object.
> CBL-3834 : Wait for listener callbacks to finish when removing listener (Port)

- README.md
Nim repo doesn't exist so removing it.
> Remove Nim repo link from README

- src/CBLCollection.cc
- src/CBLQuery_Internal.hh
- src/Listener.hh
Tagged all ListenerToken’s callback() functions as nullable.
> Fix another nullable return function warnings

- src/CBLDatabase_Internal.hh
- src/CBLQuery.cc
- src/CBLQuery_Internal.hh
- src/CBLReplicator_Internal.hh
- src/Internal.hh
- src/Listener.cc
- src/Listener.hh
* PROBLEM : There could be a race b/w explicitly removing the query’s listener token and stopping the live query when closing the database on two different threads. If the listener token is released before the the database calls the live query (a pain CBLStoppable pointer) to stop, crash will happen.
* Fixed the issue by making the database retains the CBLStoppable objects when they are registered and releases the CBLStoppable objects when they are unregistered. This will ensure that objects are alive until they are unregistered.
* Changed CBLStoppable class to have two virtual functions for retaining and releasing the object. Also renaming the stop() function to stopStoppable() for naming consistency.
* Prevented circular call to unregister live query which could lead to a deadlock.
> CBL-2914 : Crash while stopping live query when closing db

- test/CBLTest.cc
- test/CBLTest.hh
- test/CBLTest_Cpp.hh
- test/CBLTestsMain.cpp
- test/CollectionTest.cc
- test/DatabaseTest.cc
- test/DatabaseTest_Cpp.cc
- test/DocumentTest.cc
- test/LogTest.cc
- test/PerfTest.cc
- test/QueryTest.cc
- test/QueryTest_Cpp.cc
- test/ReplicatorTest.cc
* Added CBLTestAndroidContext and initAndroidContext(CBLTestAndroidContext context) function for initializing the android context. Noted that the file paths included in the context cannot be determined natively so they needed to be supplied from the Java code.
* Changed kDatabaseDir and kDatabaseConfiguration from static constants to functions so that they can use the information from the initialized android context for the android platform.
* Change the signature of ImportJSONLines() functions to accept only asset’s file name instead of path. The function will figure out the path by itself.
* Disabled the catch initializing code in CBLTestsMain.cpp for android as it will be done by android directly.
* Disabled fake replicator tests on android platform as they will behave differently …
> Make CBLTest support testing on android platform

- CBL_C.xcodeproj/project.pbxproj
- Xcode/xcconfigs/CBL_Framework.xcconfig
- Xcode/xcconfigs/CBL_Tests.xcconfig
- Xcode/xcconfigs/CBL_dylib.xcconfig
* Problem : XCode 14 starts to require code signing for command line app and dynamic lib.
* Explicitly set the code sign identity and development team to CBL_Tests and CBL_dylib target.
* Moved code signing related configs from CBL_Framework to xcconfig files.
* Removed ENABLE_HARDENED_RUNTIME and PROVISIONING_PROFILE_SPECIFIER settings to use the default values which is NO (config for app not framework) and empty respectively.
> CBL-3934 : Fix empty identity is not valid error with XCode 14

- test/CMakeLists.txt
- test/cmake/test_source_files.cmake
For sharing the test source file settings b/w CBL_Tests app and android test app (will be published in a separated PR), extract the setting test source files as a function in `cmake/test-source_files.cmake` file.
> CBL-3938 : Extract setting test src files into a shared cmake file

- include/cbl/CBLPlatform.h
* Change the recommendation for temp directory to use a directory under Context’s getFileDir which is safer to use across android API levels.
* Use the right format for multiline comment.
> CBL-3988 : Update Android CBL_Init() API Doc

- test/CollectionTest.cc
- test/CollectionTest_Cpp.cc
skipping existing tests and added a new test that checks for error when trying to delete default collection
> CBL-3983: Not allow to delete default collection

- cmake/platform_linux_desktop.cmake
It's weird that this worked at all, but it was only discovered via Jenkins
> CBL-4007: Since LITECORE_DYNAMIC_ICU is forced on, remove ICU search logic

- include/cbl++/Replicator.hh
- include/cbl/CBLReplicator.h
- src/CBLReplicatorConfig.hh
* Used #ifdef __CBL_REPLICATOR_NETWORK_INTERFACE__ to remove the networkInterface config from the public API.
* As the API is still in the header file, add a specific NOTE that the config is not supported.
> CBL-4017 : Remove networkInterface from public API

- include/cbl/CBLReplicator.h
Added note that channels are not supported in Peer-to-Peer and DB-to-DB replication.
> CBL-4090 : Add note regarding channels filter

- jenkins/ci_cross_build.py
- jenkins/couchbase-lite-c-linux-build.sh
- jenkins/linux-package-config.json
Final deliverable packages should be named just "linux-$ARCH".
The scripts and linux-package-config.json file now differentiate:
* build_os - the OS to cross-compile for, per architecture
* target_osname - the OS name to use in deliverables (linux-$ARCH)
* target_debs - OS distributions to create specific .debs for
> CBD-5234: Naming change for couchbase-lite-c .tar.gz packages

- jenkins/ci_build_win_desktop.ps1
* Removed visual studio version from cmake platform generator to use the latest visual studio installed on the machine.
* This has been tested by doing the toy build (3.1.0-50551).
> CBL-3986 : Not specify VS version in wins build script

- include/cbl/CBLReplicator.h
- test/ReplicatorPropEncTest.cc
- test/ReplicatorTest.hh
* Updated LiteCore to 3.0.9-2 to uptake the property encryption / decryption enhancement to support the retry.
* From the enhancement, we now support WebSocket/503 error returned from the callback. When the 503 error returned, the replicator will be offline, the retry logic will be triggered to allow the encryption / decryption to be retried. When a crypto or the other error returns, the document will be failed to replicate permanently.
* Added more info about returning error in prop encryption / decryption callbacks to the API comment.
* Updated `Encryption error` and `Decryption error` tests.
* Remove `status.progress.complete < 1.0` check in replicator tests as it was wrong assumption.
> CBL-4111 : Allow to retry when a transient error occurred during property encryption / decryption

- src/CBLDatabase_CAPI.cc
Replaced C4Database::getDocumentCount and getLastSequence with the C4Collection:: getDocumentCount and getLastSequence.
> CBL-4183 : Replace deprecated LiteCore API calls

- include/cbl++/Collection.hh
- include/cbl/CBLCollection.h
- src/CBLCollection_CAPI.cc
- src/CBLCollection_Internal.hh
- test/CBLTest.cc
- test/CollectionTest.cc
- test/ReplicatorCollectionTest.cc
To be consistent with the other APIs that return a scope pointer such as CBLDatabase_Scope(db, name) or CBLDatabase_DefaultScope(db), changed CBLCollection_Scope(col) to return a retained pointer.
> CBL-4198 : Make CBLCollection_Scope return a retained pointer

- src/CBLReplicatorConfig.hh
The key is set to "kCBLReplicatorUserAgent" which is accidentally incorrect. It should be "User-Agent".
> CBL-4201 : Fix incorrect User-Agent key

- src/CBLReplicatorConfig.hh
The key is set to "kCBLReplicatorUserAgent" which is wrong. It needs to be "User-Agent".
> CBL-4203 : Fix incorrect User-Agent key

- include/cbl/CBLReplicator.h
- test/ReplicatorPropEncTest.cc
- test/ReplicatorTest.hh
* Per enhancement in LiteCore 3.1.0-340, update the API to reflect the change that allows the replication to retry (offline / retry) when a property encryption / decryption callback returns WebSocket/503 error.
* Updated Property Encryption / Decryption Error Tests accordingly.
* Removed a wrong assumption check in ReplicatorTest.hh
* Noted that the change has been manually picked up and applied from the changes in lithium branch : 54be5e98f19cd95c7fc562d764434992444644ec
> CBL-4172 : Update Property Encryption / Decryption Callback API Doc

- jenkins/ci_build_android.sh
* Ported the fix from release/3.1 branch (9997b5d1cc741ebe15458e182f866ff30a73b7a5)
* Add in a missing CMAKE_BUILD_TYPE.  Until now this has been debug builds.
> CBL-3965 : Update ci_build_android.sh

- src/CBLUserAgent.hh
* Ported the fix from release/lithium branch (dcbdf3df9660eada92586a97b6cd0ad6bfbb1532); the original issue is CBL-4275.
* The crash could happen as the buffer size is too small when getting the Android SDK version with 3 digits such as 7.1.1.
* Used PROP_VALUE_MAX defined in system_properties.h instead of a fixed number for the buffer size.
> CBL-4285 : Fix crash when getting User-Agent on Android

- src/CBLUserAgent.hh
* Ported the fix from release/lithium branch (dcbdf3df9660eada92586a97b6cd0ad6bfbb1532); original issue is CBL-4275.
* The crash could happen as the buffer size is too small when getting the Android SDK version with 3 digits such as 7.1.1.
* Used PROP_VALUE_MAX defined in system_properties.h instead of a fixed number for the buffer size.
> CBL-4291 : Fix crash when getting User-Agent on Android

- include/cbl/CBLCollection.h
Corrected API doc about deleting the default collection as we do not allow to delete the default collection in 3.1 release.
> CBL-4335 : Correct API doc about deleting the default collection

- include/cbl/CBLCollection.h
* Ported the fix (2843ad75d18df62841c3f4997e84a1960bc813f4) from release/3.1 branch (CBL-4335)
* Corrected API doc about deleting the default collection as we do not allow to delete the default collection in 3.1 release.
> CBL-4340 : Correct API doc about deleting the default collection

- include/cbl/CBLReplicator.h
Tagged propertyEncryptor, propertyDecryptor, documentPropertyEncryptor, and documentPropertyDecryptor as nullable. They are optional.
> CBL-4347 : Tag prop encryptor and decryptor as nullable

- scripts/build_apple.sh
* Apple doesn’t allow to include bitcode in the binary and framework anymore.
* Removed the BITCODE_GENERATION_MODE from the apple build script.
> CBL-4509 : Remove bitcode flag from build script

- scripts/build_apple.sh
* Apple doesn’t allow to include bitcode in the binary and framework anymore.
* Removed the BITCODE_GENERATION_MODE from the apple build script.
> CBL-4489 : Remove bitcode flag from build script

- include/cbl/CBLPlatform.h
* Updated recommendation for Android’s files and temp directory.
* Ported from e99bc41537904986d9a20eb374ea8d196d8b9c25 in helium / master branch.
> CBL-3986 : Update API doc about android files / temp dir

- scripts/build_apple.sh
* Apple doesn’t allow to include bitcode in the binary and framework anymore.
* Removed the BITCODE_GENERATION_MODE from the apple build script.
* Ported from 267834a8f4e484fcab0b3b4924d1bffec4adcc60 in the master branch.
> CBL-4488 : Remove bitcode flag from build script

- include/cbl/CBLReplicator.h
* Tagged propertyEncryptor, propertyDecryptor, documentPropertyEncryptor, and documentPropertyDecryptor as nullable. They are optional. 
* Ported from baad2f18a0f935be4af71477621f52367dedcb7f in branch release/3.1.
> CBL-4348 : Tag prop encryptor and decryptor as nullable

- include/cbl++/Replicator.hh
- include/cbl/CBLReplicator.h
- src/CBLReplicatorConfig.hh
* Ported from 3de2a24cf0d98309b2b796e133ab1ca9558967b6 in the master branch.
* Update LiteCore to 3.0.12-16.
* Required some manual change to resolve the conflict when cherry-picking the commit.
> CBL-4561 : Add acceptParentDomainCookies config

- jenkins/ci_cross_build.py
It is moved as part of the process, so the implicit delete with TemporaryDirectory is closed fails
> Fix a bug where the temp directory cannot be deleted

- test/CBLTest.cc
- test/DatabaseTest.cc
- test/ReplicatorPropEncTest.cc
* Enabled verbose logging "Close Database with Active Replicator" and "Delete Database with Active Replicator" which currently failed on Jenkins's Debian 10 for investigation. The issue cannot be reproduced locally and on the other platforms.
* Changes are in the test code only.
> Enable verbose log in flaky tests

- Xcode/xcconfigs/Project.xcconfig
We are bumping the iOS target version in Beryllium to 12.0.
> CBL-5380 : Update iOS Deployment Target Version to 12.0

- src/CBLBlob_CAPI.cc
- src/CBLDatabase.cc
- src/CBLDocument.cc
- src/CBLQuery_CAPI.cc
- src/ConflictResolver.cc
- src/Listener.cc
- test/DatabaseTest_Cpp.cc
- test/QueryTest.cc
- test/QueryTest_Cpp.cc
Update the code so that the project can be built with xcode15.
> Make the code built with xcode15

- src/CBLCollection.cc
- src/CBLCollection_CAPI.cc
- src/CBLCollection_Internal.hh
- src/CBLDocument.cc
- src/CBLDocument_Internal.hh
- src/CBLPrivate.h
- src/CBLReplicatorConfig.hh
- src/CBLReplicator_Internal.hh
- src/Listener.hh
- test/DatabaseTest.cc
- test/ReplicatorEETest.cc
* Issue : When notify collection change, the code needs to obtain the database lock in order to get the database instance from the collection object. The deadlock could occurred if a document save happens at the same time on the other thread as the document save will need to wait to open its transaction while the other transaction is still opened by the notification thead.
* Solution : Keep the database pointer inside the Collection class without resetting its to null to invalidate the pointer so that there is no lock required when accessing it. As the collection objects cannot retain the database object to avoid retain cycle (collections are cached inside the database object), the database object need to be retained else where where it is being used (along side with its collection …
> CBL-5606 : Fix lock caused by saving doc and notifying change

- src/CBLReplicatorConfig.hh
- src/CBLReplicator_Internal.hh
- test/ReplicatorEETest.cc
* Ported the change from release/3.1 branch (a5ff22ea8a1513d28fe222770083907d3b8cd0cd).
* Moved the config validation call into ReplicatorConfiguration itself.
* Moved the code that generates the effective replication collections from CBLReplicator into the ReplicatorConfiguration.
* Retained collection objects inside ReplicatorConfiguration. This is important to ensure the collection life time inside the replicator object.
* Added DocIDs Push /Pull Filters tests.
> CBL-5638 : Port ReplicatorConfiguration change

- Xcode/PrivacyInfo.xcprivacy
NSPrivacyAccessedAPITypes and NSPrivacyCollectedDataTypes are required for generating the App’s privacy report even though in the Apple doc, the only required key for 3rd party SDK is NSPrivacyAccessedAPITypes. This commit adds all keys in case the other keys are required in the future by Apple.
> CBL-5526 : Add all keys to the Privacy Manifest file

- include/cbl++/Replicator.hh
- include/cbl/CBLReplicator.h
Added note that replicators cannot be started in a transaction.
> CBL-5711 : Add note that replicators cannot be started in a transaction

- include/cbl/CBLPrediction.h
- src/CBLPrediction.cc
- test/VectorSearchTest.hh
…tionary
Changed prediction callback signature to return FLMutableDict instead of FLSliceResult to be inline with the other platforms. The returned FLMutableDict will be released after the callback is called.
> CBL-5851 : Change prediction callback signature to return FLMutableDict

- include/cbl/CBLQueryIndex.h
- src/CBLQueryIndex.cc
- src/CBLQueryIndex_CAPI.cc
- src/CBLQueryIndex_Internal.hh
- src/Internal.hh
- test/LazyVectorIndexTest.cc
- test/VectorSearchTest.cc
- test/VectorSearchTest.hh
* Updated IndexUpdater API to sync illegal behavior with the other platforms : If functions have out error, return out error; otherwise abort.
* Added TestIndexUpdaterUseAfterFinished.
* Used LiteCore 3.2.0-210
> CBL-5894 : Update IndexUpdater API and sync illegal behavior

- CBL_C.xcodeproj/project.pbxproj
Added `CBLQueryIndexTypes.h` and `CBLQueryTypes.h` to the target framework.
> CBL-5955 : Fix XCFramework doesn’t include CBLQueryIndexTypes/CBLQueryTypes.h

- CBL_C.xcodeproj/project.pbxproj
@pasin It seems like this header is missing also? QE ran into the same problem again, but with this header.
> CBL-5966: CBLPrediction.h header missing from xcproject

- include/cbl/CBLDatabase.h
- src/CBLDatabase_Internal.hh
- test/DatabaseTest.cc
* Cherry-Picked the change from cce49636faccc9358249d574b9cea1d658059a7f in release/3.1 branch. There was a conflict in DatabaseTest.cc which is easy to resolve.
* Implemented FullSync DatabaseConfiguration property.
* No change to C++ Public API as it uses C's CBLDatabaseConfiguration directory.
* Updated LiteCore to 3.2.0-223
> CBL-6071 : Implement FullSync DatabaseConfiguration property

- Xcode/CouchbaseLite.modulemap
Included the missing header files.
> CBL-6160 : Fix CouchbaseLite.modulemap

- jenkins/cross_manifest.json
- jenkins/linux-package-config.json
This required an intensive rebuild from the scripts downstream, and moving the result to a place that we control.  Re-enable raspbian9.
> The raspbian 9 compiler vanished from sourceforge so host it

- include/cbl++/Document.hh
- include/cbl/CBLDocument.h
- src/CBLDatabase_Internal.hh
- src/CBLDocument_CAPI.cc
- src/CBLDocument_Internal.hh
- src/CBLPrivate.h
- src/CBLUserAgent.hh
- src/ConflictResolver.cc
- src/exports/CBL_Exports.txt
- src/exports/generated/CBL.def
- src/exports/generated/CBL.exp
- src/exports/generated/CBL.gnu
- src/exports/generated/CBL_Android.gnu
- src/exports/generated/CBL_EE.def
- src/exports/generated/CBL_EE.exp
- src/exports/generated/CBL_EE.gnu
- src/exports/generated/CBL_EE_Android.gnu
- test/DocumentTest.cc
- test/ReplicatorCollectionTest.cc
- test/ReplicatorEETest.cc
* Enable Version Vector (CBL-6213).
* Implement Document’s timestamp (CBL-6217).
* Implement new default conflict resolver (CBL-6221).
* (Private) Implement Document’s getRevisionHistory().
* (Private) Temporarily add Documenent’s getGlobalRevisionID() until the issue with * id is sorted out for testing.
* Fix Compile error in CBLUserAgent.hh.
* Update LiteCore to the latest master (92fc5cc)
> CBL-6213 : Enable Version Vector

- jenkins/cross_manifest.json
* Rasbian 9 toolchain was removed from the 3rd party website. Update the URL to use internal built toolchain instead.
* Ported this change from release/3.2 (1b8799a89b390ab5e8aca2863d85c250379099b3)
> Update raspbian 9 compiler

- test/DatabaseTest.cc
- test/QueryTest.cc
* Update LiteCore to 4.0.9-19.
* Reenabled Test Joins with Collections Test's Use Full Collection Name section as CBL-6243 has been fixed in 4.0.0-10.
> Update LiteCore to 4.0.0-19

- .github/workflows/build_android.yml
- test/platforms/Android/app/CMakeLists.txt
- test/platforms/Android/app/build.gradle
- test/platforms/Android/app/src/main/cpp/native-lib.cpp
* Updated to use macos-13
* Used the new Android cmd_tools to install the SDK and tool required.
* Updated NDK and CMake version to be able to compile modern C++ codes in LiteCore and Fleece.
* Fix Android Test’s code that runs catch tests.
> CBL-6651 : Fix and enable android GHA PR Validation

- include/cbl/CBLQueryIndexTypes.h
- src/CBLCollection_Internal.hh
- test/QueryTest.cc
* Implement the partial index API and tests.
* Ensure to include null-terminated char when converting from FLString to const char* when using LiteCore C4 Index API (CBL-6669).
* Update LiteCore to 3.2.2-3.
> CBL-5191 : Implement the partial index API

- src/CBLBase_CAPI.cc
- src/CBLLogSinks.cc
- src/CBLPrivate.h
- src/exports/CBL_Exports.txt
- src/exports/generated/CBL.def
- src/exports/generated/CBL.exp
- src/exports/generated/CBL.gnu
- src/exports/generated/CBL_Android.gnu
- src/exports/generated/CBL_EE.def
- src/exports/generated/CBL_EE.exp
- src/exports/generated/CBL_EE.gnu
- src/exports/generated/CBL_EE_Android.gnu
- test/LogTest.cc
CBL-C doesn’t automatically create the specified log directory if it doesn’t exist while the other platforms do. This commit enhances the log  (both old and log sink api) to create the log directory if it doesn’t exist.
> CBL-6678 : Auto create log directory

- CBL_C.xcodeproj/project.pbxproj
Set the target level of CBLLogSinks.h to public in the XCode Project.
> Fix missing CBLLogSinks.h header in iOS framework

- CBL_C.xcodeproj/project.pbxproj
- CBL_C.xcodeproj/xcshareddata/xcschemes/CBL_Tests.xcscheme
* Instead of adding Fleece's Catch2 as a target dependency to the CBL_Tests target (This somehow doesn’t work as XCode will reference to the Fleece project using the absolute path), link libCatch2.a directly from the General tab of the CBL_Tests target.
* Edit CBL_Tests scheme by enabling `Find Implicit Dependencies` option so that XCode can automatically include Fleece's Catch2 target as the dependency without a need to explicitly adding to the target dependencies list.
> Fix Catch2 target dependencies

- src/CBLCollection_Internal.hh
- src/CBLDocument.cc
- src/CBLDocument_Internal.hh
- test/DocumentTest.cc
* For CBSE-19553
* Relaxed the validation rule to allow docs from different instances of the same collection (but from the same db instance) to save or delete.
* This validation is inline with .NET and JAX implementation.
> CBL-6817 :  Allow docs from different instances of the same collection to save or delete

- include/cbl++/Collection.hh
When C++23 is enabled (CMAKE_CXX_STANDARD=23) there are errors such as:
```
error: allocation of incomplete type 'cbl::CollectionChange'
```
The problem appears to be related to `std::make_unique` becoming constexpr in C++23; this change fixes the build for C++23 by ensuring `std::make_unique` is called after the types are fully defined.
> Fix C++23 build errors due to std::make_unique on forward declared class

- CBL_C.xcodeproj/project.pbxproj
- CMakeLists.txt
- include/cbl/CBLTLSIdentity.h
- src/CBLDatabase_CAPI.cc
- src/CBLDatabase_Internal.hh
- src/CBLPrivate.h
- src/CBLTLSIdentity_CAPI.cc
- src/CBLTLSIdentity_Internal.hh
- src/CBLURLEndpointListener.cc
- src/CBLURLEndpointListener_CAPI.cc
- src/CBLURLEndpointListener_Internal.hh
- src/exports/CBL_Exports.txt
- src/exports/generated/CBL.def
- src/exports/generated/CBL.exp
- src/exports/generated/CBL.gnu
- src/exports/generated/CBL_Android.gnu
- src/exports/generated/CBL_EE.def
- src/exports/generated/CBL_EE.exp
- src/exports/generated/CBL_EE.gnu
- src/exports/generated/CBL_EE_Android.gnu
- test/CMakeLists.txt
- test/URLEndpointListenerTest.cc
For Linux or Android, we create an self-signed TLS Identity whose life attached to the Listener. For other platforms, we will save the Identity by label being the UUID of the database.
> CBL-6885: Anonymous TLS Identity for URLEndpointListener

- src/CBLDatabase.cc
- src/CBLDatabase_Internal.hh
- src/CBLQuery.cc
- src/CBLQuery_Internal.hh
- src/CBLReplicator_Internal.hh
- src/CBLURLEndpointListener.cc
- src/Internal.hh
* Registered the listener as an active service when it’s started successfully so that the database can stop the listener when it’s closed.
* Refactored so that each stoppable service doesn’t need to implement a subclass of the CBLStoppable and used Retained<CBLRefCounted> instead of manually calling retain() and release().
* Renamed CBLStoppable to CBLActiveService.
> CBL-6922 : Allow database to stop listener when closing

- include/cbl++/Base.hh
- include/cbl/CBLBase.h
- include/cbl/CBLBlob.h
- include/cbl/CBLEncryptable.h
- include/cbl/CBL_Compat.h
The use of 'static' on these functions isn't necessary in C++ and prevents re-exporting them from a C++20 module (by #include of cbl in the global module fragment and then `export using ...;` for relevant names).
Notes:
* operator==(CBLError, CBLError) doesn't use the CBLINLINE macro because it is already in a C++ context
* There was an existing CBLINLINE macro (apparently unused), which has been renamed to CBLFORCEINLINE
> Remove 'static' from inline API functions when compiling with C++

- CBL_C.xcodeproj/project.pbxproj
Made CBLURLEndpointListener.h and CBLTLSIdentity.h public in the XCode target otherwise the headers will not be included in the XCFramework file.
> Fix headers missing in xcframework

- src/CBLLogSinks.cc
- src/CBLLogSinks_Internal.hh
* Lazily construct and cache full list of log domains lazily instead of doing it in the init() function and ensure that the full list of the log domains is ready before being accessed.
* Remove a workaround to populate the listener domain to a const array.
> Lazily construct full list of log domains

- include/cbl/CBLURLEndpointListener.h
- src/CBLURLEndpointListener_CAPI.cc
- test/URLEndpointListenerTest.cc
* Add context param to CBLListenerAuth_CreatePassword and  CBLListenerAuth_CreateCertificate so that the callback context is decouple from CBLURLEndpointListenerConfiguration.
* Remove context from CBLURLEndpointListenerConfiguration.
* Pass CBLCert object instead of cert data to CBLListenerCertAuthCallback.
> Minor adjustment to URLEndpointListener API

- Xcode/xcconfigs/Project.xcconfig
The correct macOS target version since CBL-C 3.2 is 12.0 not 10.14.
> CBL-6927 : Corrected macOS target version to 12.0.

- include/cbl/CBLTLSIdentity.h
- src/CBLTLSIdentity_CAPI.cc
- src/exports/CBL_EE_Exports.txt
- src/exports/generated/CBL_EE.def
- src/exports/generated/CBL_EE.exp
- src/exports/generated/CBL_EE.gnu
- src/exports/generated/CBL_EE_Android.gnu
- test/TLSIdentityTest.cc
- test/URLEndpointListenerTest.cc
To make it easier to understand and make the context object make sense, change the signature as follows:
* Rename the callback to CBLExternalKeyCallbacks.
* For each callback function, rename context param to externalKey.
* Rename CBLKeyPair_CreateWithCallbacks to CBLKeyPair_CreateWithExternalKey.
* Rename context param to externalKey and move the param before callbacks.
* In CBLTLSIdentity_IdentityWithKeyPairAndCerts, keypair is not nullable.
> Change CBLKeyPair_CreateWithCallbacks Signature

- CMakeLists.txt
Workaround to avoid crash when locking mutex on VC++ Runtime version < 14.4.
> CBL-6932 : Disable constexpr mutex constructor for windows build

- test/URLEndpointListenerTest.cc
Fixed a bug caused by failure to copy the listener configuration to the listener.
> CBL-6950: Crash when stopping listener

- src/CBLReplicatorConfig.hh
- test/ReplicatorTest.cc
To support URLEndpointListener, we need to relax the validation rules for database names. Since Couchbase Lite does not enforce strict naming rules for databases, we can only validate that a database name is present in the URL path, without applying additional constraints.
> CBL-6951 : Relax database validation rules in URLEndpoint

- src/CBLReplicatorConfig.hh
- test/ReplicatorTest.cc
* Relaxing the rules in URLEndpoint alone is not enough. C4Replicator also performs the same validation when the internal socket factor is used. Will leave this as an open issue for 3.2.3.
* This reverts commit 0aa1b195312a11b21d03d59e8351301f30543c01.
> Revert "CBL-6951 : Relax database validation rules in URLEndpoint"

- cmake/platform_android.cmake
Ported linker flags from LiteCore to support Android 16 KB Page (See https://github.com/couchbase/couchbase-lite-core/commit/d4580f0acea7c0f96d6ce85b076a2ecc2528981d).
> Update Android LINK_FLAGS to support 16 KB page sizes

- include/cbl/CBLTLSIdentity.h
* Updated CBLExternalKeyCallbacks’s publicKeyData info to be more accurate about the format.
* Updated LiteCore to 3.2.4-3
> Update external key callback’s publicKeyData info and LiteCore

- include/cbl/CBLLog.h
- src/CBLLog.cc
- src/CBLLogSinks.cc
- src/CBLLogSinks_CAPI.cc
- src/CBLLogSinks_Internal.hh
- src/exports/CBL_Exports.txt
- src/exports/generated/CBL.def
- src/exports/generated/CBL.exp
- src/exports/generated/CBL.gnu
- src/exports/generated/CBL_Android.gnu
- src/exports/generated/CBL_EE.def
- src/exports/generated/CBL_EE.exp
- src/exports/generated/CBL_EE.gnu
- src/exports/generated/CBL_EE_Android.gnu
- test/LogTest.cc
- test/LogTest_Cpp.cc
* Removed deprecated Logging API.
* Simplified locking mechanism and how to get and cache C4LogDomain objects in CBLLogSinks.cc.
* Updated tests.
> CBL-7314 : Remove deprecated Logging API

- include/cbl/CBLLog.h
- include/cbl/CBLLogSinks.h
* The section header should be LogSinks instead Logging and shouldn’t be marked as deprecated.
* Removed deprecated from Logging header to avoid confusion in the future if we add a new non-deprecated methods in that section.
> CBL-7133 : Fix LogSink API doc section header

- jenkins/ci_build_android.sh
* CBL-C’s Unix CMake build already inherits the MinSizeRel flag overrides from LiteCore (see [this](https://github.com/couchbase/couchbase-lite-core/blob/master/cmake/platform_unix.cmake#L9-L16)), so no additional changes are required in CBL-C’s CMake.
* Do not strip the native symbols in the android released build script.
* The binary size increased by ~10×. After running `$objcopy --strip-debug libcblite.so`, the resulting libcblite.so is about the same size as the previously stripped binary. 
* Info from using file command :
- Current Build :
```
libcblite.so: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, BuildID[sha1]=35b319272d06750e6ba9c054ebb6346178f0c7a1, with debug_info, not stripped 
```
- Previous Build (Stripped):
```
libcblite.so: ELF 64-bit …
```
> CBL-7431 : Include native symbols in android released binaries

- jenkins/ci_build_unix.sh
- jenkins/ci_build_win_desktop.ps1
* Updated CI build script for windows to have an option to skip running tests using SKIP_TESTS env.
* Updated CI build script for unix platform to also skip downloading vector search extension when SKIP_TEST is enabled.
* This is a temporary workaround until build issue on vector search extension for windows is resolved.
> Add an option to skip running tests in Windows build script
